homeSuccess:
  javascripts:
    op_opensocial_prototype: %SF_PROTOTYPE_WEB_DIR%/js/prototype
    op_opensocial_rpc:       /gadgets/js/rpc.js?c=1
    op_opensocial_tab:       /opOpenSocialPlugin/js/tabs-min
    op_opensocial_container: /opOpenSocialPlugin/js/container
