homeSuccess:
  javascripts:
    - /application/webprefix
    - /gadgets/js/rpc.js?c=1
    - %SF_PROTOTYPE_WEB_DIR%/js/prototype
    - /opOpenSocialPlugin/js/tabs-min
    - /opOpenSocialPlugin/js/container
